import { Router } from 'express'; import bcrypt from 'bcrypt'; import jwt, { type SignOptions } from 'jsonwebtoken'; import type { RowDataPacket } from 'mysql2/promise'; import { db } from '../config/db.js'; import { env } from '../config/env.js'; import { requireAuth } from '../middleware/auth.js'; import { fail,ok } from '../utils/http.js';
export const authRouter=Router();
const cookie={httpOnly:true,secure:env.NODE_ENV==='production',sameSite:'lax' as const,path:'/'};
function tokens(user:{id:number;username:string;role:string}){const payload={id:user.id,username:user.username,role:user.role};return {access:jwt.sign(payload,env.JWT_SECRET,{expiresIn:env.JWT_EXPIRES_IN as SignOptions['expiresIn']}),refresh:jwt.sign(payload,env.JWT_REFRESH_SECRET,{expiresIn:env.JWT_REFRESH_EXPIRES_IN as SignOptions['expiresIn']})};}
authRouter.post('/login',async(req,res,next)=>{try{const {username,password}=req.body;if(!username||!password)return fail(res,'Username and password are required',422);const [rows]=await db.execute<RowDataPacket[]>('SELECT id,username,email,password_hash,role,is_active FROM admin_users WHERE username=? LIMIT 1',[username]);const u=rows[0];if(!u||!u.is_active||!(await bcrypt.compare(password,u.password_hash)))return fail(res,'Invalid username or password',401);const t=tokens(u as never);await db.execute('UPDATE admin_users SET last_login_at=NOW() WHERE id=?',[u.id]);res.cookie('access_token',t.access,{...cookie,maxAge:3600000}).cookie('refresh_token',t.refresh,{...cookie,maxAge:604800000});return ok(res,{user:{id:u.id,username:u.username,email:u.email,role:u.role}} ,'Login successful');}catch(e){next(e);}});
authRouter.post('/refresh',(req,res)=>{try{const u=jwt.verify(req.cookies?.refresh_token||'',env.JWT_REFRESH_SECRET) as {id:number;username:string;role:string};const t=tokens(u);res.cookie('access_token',t.access,{...cookie,maxAge:3600000});return ok(res,{} ,'Session refreshed');}catch{return fail(res,'Invalid refresh token',401);}});
authRouter.post('/logout',(req,res)=>{res.clearCookie('access_token',cookie).clearCookie('refresh_token',cookie);return ok(res,{},'Logged out');});
authRouter.get('/me',requireAuth,async(req,res,next)=>{try{const [rows]=await db.execute<RowDataPacket[]>('SELECT id,username,email,role,last_login_at FROM admin_users WHERE id=?',[req.user!.id]);return ok(res,rows[0]);}catch(e){next(e);}});
authRouter.post('/change-password',requireAuth,async(req,res,next)=>{try{const {currentPassword,newPassword}=req.body;if(typeof newPassword!=='string'||newPassword.length<10)return fail(res,'New password must be at least 10 characters',422);const [rows]=await db.execute<RowDataPacket[]>('SELECT password_hash FROM admin_users WHERE id=?',[req.user!.id]);if(!rows[0]||!(await bcrypt.compare(currentPassword,rows[0].password_hash)))return fail(res,'Current password is incorrect',400);await db.execute('UPDATE admin_users SET password_hash=? WHERE id=?',[await bcrypt.hash(newPassword,12),req.user!.id]);res.clearCookie('access_token',cookie).clearCookie('refresh_token',cookie);return ok(res,{},'Password changed; sign in again');}catch(e){next(e);}});

