-- Editable demonstration content. No administrator password is stored here.
INSERT INTO profiles (owner_name,profession,company,short_intro,full_bio,email,phone,location) VALUES ('Touhid Rahman','Human Resources & Administration Professional','Your Organization','Building people-first workplaces through practical HR leadership.','<p>I help organizations strengthen people operations, employee experience, compliance, and administration. Every value on this site can be replaced from SmartPortfolio Admin.</p>','hello@example.com','+880 1XXX-XXXXXX','Dhaka, Bangladesh');
INSERT INTO website_settings (site_title,site_tagline,domain,footer_text,copyright_text,developer_credit,resume_button_text) VALUES ('Touhid Rahman','People. Process. Progress.','https://touhidhr.com','A configurable professional portfolio powered by SmartPortfolio.','© 2026. All rights reserved.','Powered by SmartPortfolio','Download Resume');
INSERT INTO theme_settings (preset,mode) VALUES ('Executive Navy','system');
INSERT INTO theme_presets (name,tokens) VALUES
('Corporate Blue',JSON_OBJECT('primary_color','#2563eb','secondary_color','#0f172a','accent_color','#14b8a6','background_color','#f8fafc','surface_color','#ffffff')),
('Executive Navy',JSON_OBJECT('primary_color','#1d4ed8','secondary_color','#07152e','accent_color','#0ea5a4','background_color','#f5f7fb','surface_color','#ffffff')),
('Modern Green',JSON_OBJECT('primary_color','#059669','secondary_color','#064e3b','accent_color','#f59e0b','background_color','#f6fbf8','surface_color','#ffffff')),
('Elegant Purple',JSON_OBJECT('primary_color','#7c3aed','secondary_color','#2e1065','accent_color','#db2777','background_color','#faf7ff','surface_color','#ffffff')),
('Premium Dark',JSON_OBJECT('primary_color','#d4a853','secondary_color','#05070b','accent_color','#e5c477','background_color','#090d14','surface_color','#121824')),
('Minimal Light',JSON_OBJECT('primary_color','#18181b','secondary_color','#27272a','accent_color','#71717a','background_color','#fafafa','surface_color','#ffffff')),
('Developer Dark',JSON_OBJECT('primary_color','#22c55e','secondary_color','#020617','accent_color','#38bdf8','background_color','#090e1a','surface_color','#111827')),
('Creative Portfolio',JSON_OBJECT('primary_color','#f43f5e','secondary_color','#312e81','accent_color','#f59e0b','background_color','#fff7ed','surface_color','#ffffff'));
INSERT INTO layout_settings () VALUES ();
INSERT INTO seo_settings (meta_title,meta_description,keywords,canonical_domain,og_image,indexing_enabled) VALUES ('Touhid Rahman — HR & Administration Professional','Portfolio, experience, insights, and contact information.','HR, administration, people operations, portfolio','https://touhidhr.com','/og.png',1);
INSERT INTO about (title,subtitle,content,facts) VALUES ('A practical partner for people and operations','Human-centered systems, measurable outcomes.','<p>Experienced across recruitment, employee relations, policy, operations, and organizational development.</p>',JSON_ARRAY(JSON_OBJECT('label','Years of experience','value','8+'),JSON_OBJECT('label','People supported','value','500+')));
INSERT INTO menus (label,target_type,target,display_order) VALUES ('Home','section','#home',1),('About','section','#about',2),('Experience','section','#experience',3),('Services','section','#services',4),('Insights','url','/posts',5),('Contact','section','#contact',6);
INSERT INTO sections (section_key,title,subtitle,layout_style,display_order) VALUES ('hero','Hello, I am Touhid','HR & Administration Professional','split',1),('about','About','A little about my work','split',2),('experience','Experience','Roles and impact','timeline',3),('skills','Capabilities','Areas of focus','cards',4),('services','Services','How I can help','cards',5),('projects','Selected Work','Programs and initiatives','grid',6),('testimonials','Testimonials','Words from colleagues','cards',7),('posts','Latest Insights','Ideas for better workplaces','grid',8),('contact','Let’s connect','Start a conversation','split',9);
INSERT INTO experiences (organization,designation,department,employment_type,start_date,current_flag,location,responsibilities,achievements,display_order) VALUES ('Example Organization','HR & Administration Manager','People & Operations','Full-time','2021-01-01',1,'Dhaka','<ul><li>Lead people operations and administration.</li><li>Strengthen policy, hiring, and employee experience.</li></ul>','Improved process visibility and employee service delivery.',1),('Previous Organization','Senior HR Officer','Human Resources','Full-time','2018-01-01',0,'Dhaka','Supported recruitment, onboarding, payroll coordination, and engagement.','Introduced repeatable onboarding checklists.',2);
INSERT INTO educations (degree,subject,institute,result,start_date,end_date,description,display_order) VALUES ('Master of Business Administration','Human Resource Management','Example University','Completed','2016-01-01','2018-01-01','Focused on strategic human resources and organizational development.',1);
INSERT INTO skill_categories (name,slug,display_order) VALUES ('Human Resources','human-resources',1),('Administration','administration',2);
INSERT INTO skills (category_id,name,level,percentage,description,display_order) VALUES (1,'People Operations','Advanced',90,'Employee lifecycle and service delivery.',1),(1,'Talent Acquisition','Advanced',88,'Structured hiring and onboarding.',2),(2,'Policy & Compliance','Advanced',86,'Practical controls and documentation.',3),(2,'Office Administration','Advanced',92,'Reliable facilities and vendor operations.',4);
INSERT INTO services (title,slug,icon,short_description,description,cta_label,cta_url,display_order) VALUES ('HR Operations Review','hr-operations-review','bi-diagram-3','Assess and strengthen core people processes.','<p>A structured review of current practices with prioritized recommendations.</p>','Discuss a review','#contact',1),('Policy & SOP Development','policy-sop-development','bi-journal-check','Clear, usable policies and operating procedures.','<p>Documentation designed for real teams and practical adoption.</p>','Start a project','#contact',2),('Recruitment Support','recruitment-support','bi-people','Build a consistent, candidate-friendly hiring process.','<p>Role definition, interview structure, selection, and onboarding support.</p>','Get support','#contact',3);
INSERT INTO project_categories (name,slug,display_order) VALUES ('People Operations','people-operations',1);
INSERT INTO projects (category_id,title,slug,excerpt,details,client,project_date,technologies,featured,display_order) VALUES (1,'Employee Onboarding Redesign','employee-onboarding-redesign','A clearer path from offer acceptance to a confident first 90 days.','<p>Mapped the onboarding journey, assigned ownership, and established feedback checkpoints.</p>','Confidential Organization','2025-02-01',JSON_ARRAY('Process design','Employee experience','Documentation'),1,1);
INSERT INTO achievements (title,organization,achievement_date,description,display_order) VALUES ('People Operations Excellence','Example Organization','2024-12-01','Recognized for strengthening service delivery and process ownership.',1);
INSERT INTO testimonials (person_name,designation,organization,rating,testimonial,display_order) VALUES ('A. Colleague','Operations Director','Example Organization',5,'A thoughtful professional who turns complex people challenges into practical systems.',1);
INSERT INTO clients (name,description,display_order) VALUES ('Example Organization','Demonstration client entry — replace from Admin.',1);
INSERT INTO post_categories (name,slug,description,display_order) VALUES ('Career Advice','career-advice','Practical guidance for professionals.',1),('People Operations','people-operations','Ideas for effective workplaces.',2);
INSERT INTO tags (name,slug) VALUES ('HR','hr'),('Career','career'),('Leadership','leadership');
INSERT INTO posts (category_id,title,slug,excerpt,content,author,publish_date,status,featured,seo_title,seo_description) VALUES (1,'Five ways to make onboarding more human','five-ways-to-make-onboarding-more-human','Simple improvements that help new colleagues feel informed, welcomed, and ready.','<h2>Begin before day one</h2><p>Useful onboarding starts with clear communication, access preparation, and a realistic first-week plan.</p><h2>Assign real ownership</h2><p>Give each step an owner and invite feedback after 30, 60, and 90 days.</p>','Touhid Rahman',NOW(),'published',1,'Five ways to make onboarding more human','Practical onboarding improvements for better employee experience.');
INSERT INTO post_tag_mapping (post_id,tag_id) VALUES (1,1),(1,2);
INSERT INTO social_links (platform,label,url,icon,display_order) VALUES ('LinkedIn','LinkedIn','https://www.linkedin.com/','bi-linkedin',1),('Email','Email','mailto:hello@example.com','bi-envelope',2);
