import type { ResultSetHeader,RowDataPacket } from 'mysql2/promise'; import { db } from '../config/db.js'; import { cleanHtml } from '../utils/content.js';
export const resources={experiences:'experiences',educations:'educations','skill-categories':'skill_categories',skills:'skills',certifications:'certifications',projects:'projects',services:'services',achievements:'achievements',testimonials:'testimonials',clients:'clients',menus:'menus',sections:'sections',pages:'custom_pages','custom-sections':'custom_sections','custom-section-items':'custom_section_items',resumes:'resumes','social-links':'social_links','project-categories':'project_categories','post-categories':'post_categories',tags:'tags'} as const;
export type Resource=keyof typeof resources; const blocked=new Set(['id','created_at','updated_at','password_hash']); const rich=new Set(['content','description','details','responsibilities','achievements','bio','full_bio','rich_text','testimonial']);
export function safePayload(body:Record<string,unknown>){return Object.fromEntries(Object.entries(body).filter(([k,v])=>!blocked.has(k)&&/^[a-z_]+$/.test(k)&&v!==undefined).map(([k,v])=>[k,rich.has(k)?cleanHtml(v):v]));}
const searchColumn:Record<Resource,string>={experiences:'organization',educations:'degree','skill-categories':'name',skills:'name',certifications:'title',projects:'title',services:'title',achievements:'title',testimonials:'person_name',clients:'name',menus:'label',sections:'title',pages:'title','custom-sections':'title','custom-section-items':'title',resumes:'title','social-links':'platform','project-categories':'name','post-categories':'name',tags:'name'};
export async function list(resource:Resource,query:Record<string,unknown>){const table=resources[resource],page=Math.max(1,Number(query.page)||1),limit=Math.min(100,Math.max(1,Number(query.limit)||20)),offset=(page-1)*limit;const params:any[]=[];let where='';if(query.search){where=` WHERE \`${searchColumn[resource]}\` LIKE ?`;params.push(`%${query.search}%`);}if(query.slug){where+=(where?' AND':' WHERE')+' slug=?';params.push(String(query.slug));}const [rows]=await db.query<RowDataPacket[]>(`SELECT * FROM \`${table}\`${where} ORDER BY COALESCE(display_order,0),id DESC LIMIT ? OFFSET ?`,[...params,limit,offset]);const [count]=await db.query<RowDataPacket[]>(`SELECT COUNT(*) total FROM \`${table}\`${where}`,params);return {items:rows,pagination:{page,limit,total:Number(count[0]?.total||0)}};}
export async function one(resource:Resource,id:number){const [rows]=await db.query<RowDataPacket[]>(`SELECT * FROM \`${resources[resource]}\` WHERE id=?`,[id]);return rows[0];}
export async function create(resource:Resource,body:Record<string,unknown>){const data=safePayload(body),keys=Object.keys(data);if(!keys.length)throw Object.assign(new Error('No valid fields supplied'),{status:422});const values:any[]=Object.values(data);const [r]=await db.execute<ResultSetHeader>(`INSERT INTO \`${resources[resource]}\` (${keys.map(k=>`\`${k}\``).join(',')}) VALUES (${keys.map(()=>'?').join(',')})`,values);return one(resource,r.insertId);}
export async function update(resource:Resource,id:number,body:Record<string,unknown>){const data=safePayload(body),keys=Object.keys(data);if(!keys.length)throw Object.assign(new Error('No valid fields supplied'),{status:422});const values:any[]=[...Object.values(data),id];await db.execute(`UPDATE \`${resources[resource]}\` SET ${keys.map(k=>`\`${k}\`=?`).join(',')} WHERE id=?`,values);return one(resource,id);}
export async function remove(resource:Resource,id:number){const [r]=await db.execute<ResultSetHeader>(`DELETE FROM \`${resources[resource]}\` WHERE id=?`,[id]);return r.affectedRows>0;}
